# Generated by Django 3.1.4 on 2020-12-17 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_remove_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
