# Generated by Django 3.1.4 on 2021-01-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_auto_20210124_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='resume',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
