# Generated by Django 3.1.4 on 2021-02-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_aboutme_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
