# Generated by Django 2.1.1 on 2021-09-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0014_post_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_title',
            field=models.BooleanField(default=True),
        ),
    ]
