"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 3.2.dev20200915094059.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

from pathlib import Path
import os
# from .settings_local import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '6tzd&u@)aigf6p&nxhujvalb!h+uo8(i9-t8zc=$5dd(09#in('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'theblog',
    'ckeditor',
    'storages',
]
# AWS_STORAGE_BUCKET_NAME='caitlin-blog-media'
# AWS_S3_REGION_NAME='us-east-1'
# # AWS_S3_CUSTOM_DOMAIN='caitlin-blog-media.s3.amazonaws.com'
# AWS_S3_FILE_OVERWRITE=False 
# AWS_DEFAULT_ACL=None 

# AWS_LOCATION = 'static'
# STATIC_ROOT='/static/'
# STATICFILESDIRS=[
#     os.path.join(BASE_DIR,'static'),  
#     '../theblog/static',
# ]
# # MEDIA_URL = 'http://newvirt.eba-ksnxphqp.us-east-1.elasticbeanstalk.com/'+'media/'
# # MEDIA_ROOT = MEDIA_URL

# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# STATIC_URL = 'http://newvirt.eba-ksnxphqp.us-east-1.elasticbeanstalk.com/'+'static/'
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# ADMIN_MEDIA_PREFIX = STATIC_URL + 'admin/'
# # DEFAULT_FILE_STORAGE = 'blog.storage_backends.MediaStorage'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'ebdb',
#         'USER':'DBUser',
#         'PASSWORD':'bsjoca1965',
#         'HOST':'aatsxodkv2rh64.cffnqorxelzr.us-east-1.rds.amazonaws.com',
#         'PORT':'5432',
#     }
# }
# if 'RDS_DB_NAME' in os.environ:
#     DATABASES = {
#         'default': {
#             'ENGINE': 'PostgreSQL',
#             'NAME': os.environ['aaanofk4p3eimm'],
#             'USER': os.environ['DBUser'],
#             'PASSWORD': os.environ['bsjoca1965'],
#             'HOST': os.environ['RDS_HOSTNAME'],
#             'PORT': os.environ['RDS_PORT'],
#         }
#     }
# else:
# DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql_psycopg2',
#             'NAME': 'CAITLIN_DB',
#             'USER': 'CAITLIN_BLOG_SERVER',
#             'PASSWORD': 'bsjoca1965',
#             'HOST': 'localhost',
#             'PORT': '5432',
#         }
#     }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = '/staticfiles/'

STATICFILESDIRS=[
    os.path.join(BASE_DIR,'staticfiles'),  
    '../theblog/staticfiles',
]
STATIC_ROOT='/staticfiles/'
MEDIA_URL='/media/'

MEDIA_ROOT=os.path.join(BASE_DIR,'media')
import os
if '/app' in os.environ['HOME']:
    import django_heroku
    django_heroku.settings(locals())