# Generated by Django 3.1.4 on 2020-12-17 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_auto_20201216_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
    ]
